# A reusable workflow
name: Build and push docker

on:
  push:

jobs:
  reusable-build-push:
    name: Build and push docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: lowercase username
        env:
          owner: ${{ github.repository_owner }}
        run: |
          echo "user_lc=${owner,,}" >> ${GITHUB_ENV}
          cp docker/Dockerfile1 Dockerfile
        shell: bash
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          context: .
          build-args: |
            PYPI=https://pypi.org/simple
          tags: |
            ghcr.io/${{ env.user_lc }}/label-meerkat:latest